const APP: any = {
  NAME: process.env.APP_NAME ?? '管理平台',
  DESCRIPTION: process.env.APP_DESCRIPTION ?? '© copyright 2022 超级科技版权所有',
  VERSION: process.env.APP_VERSION,
  VER: process.env.APP_VER ?? '1.7.0',
  ENV: process.env.APP_ENV ?? 'MASTER',
  STORAGE: process.env.APP_STORAGE ?? true, // 是否需要清理客户端缓存

  SRC:
    process.env.APP_SRC ??
    'data:image/svg+xml;base64,PHN2ZyBjbGFzcz0ic3ZnLWljb24iIHN0eWxlPSJ3aWR0aDogMWVtOyBoZWlnaHQ6IDFlbTt2ZXJ0aWNhbC1hbGlnbjogbWlkZGxlO2ZpbGw6IGN1cnJlbnRDb2xvcjtvdmVyZmxvdzogaGlkZGVuOyIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxwYXRoIGQ9Ik04OTYgMjEzLjMzMzMzM3YyODEuNmwtMTI4LTEyOC0xNzAuNjY2NjY3IDE3MC42NjY2NjctMTcwLjY2NjY2Ni0xNzAuNjY2NjY3LTE3MC42NjY2NjcgMTcwLjY2NjY2Ny0xMjgtMTI4VjIxMy4zMzMzMzNjMC00Ni45MzMzMzMgMzguNC04NS4zMzMzMzMgODUuMzMzMzMzLTg1LjMzMzMzM2g1OTcuMzMzMzM0YzQ2LjkzMzMzMyAwIDg1LjMzMzMzMyAzOC40IDg1LjMzMzMzMyA4NS4zMzMzMzN6IG0tMTI4IDI3My4wNjY2NjdsMTI4IDEyOFY4MTAuNjY2NjY3YzAgNDYuOTMzMzMzLTM4LjQgODUuMzMzMzMzLTg1LjMzMzMzMyA4NS4zMzMzMzNIMjEzLjMzMzMzM2MtNDYuOTMzMzMzIDAtODUuMzMzMzMzLTM4LjQtODUuMzMzMzMzLTg1LjMzMzMzM1Y1MjkuMDY2NjY3bDEyOCAxMjggMTcwLjY2NjY2Ny0xNzAuNjY2NjY3IDE3MC42NjY2NjYgMTcwLjY2NjY2NyAxNzAuNjY2NjY3LTE3MC42NjY2Njd6IiAgZmlsbD0iI2UwZTBlMCIvPjwvc3ZnPg==',
  CODES: [
    { cn: '菲律宾', en: 'Philippines', code: '63', name: 'PH' },
    { cn: '柬埔寨', en: 'Cambodia', code: '855', name: 'KH' },
    { cn: '中国', en: 'China', code: '86', name: 'CN' },
    { cn: '中国香港', en: 'Hong Kong', code: '852', name: 'HK' },
    { cn: '中国澳门', en: 'Macao', code: '853', name: 'MO' },
    { cn: '中国台湾', en: 'Taiwan', code: '886', name: 'TW' },
    { cn: '日本', en: 'Japan', code: '81', name: 'JP' },
    { cn: '阿富汗', en: 'Afghanistan', code: '93', name: 'AF' },
    { cn: '阿尔巴尼亚', en: 'Albania', code: '355', name: 'AL' },
    { cn: '阿尔及利亚', en: 'Algeria', code: '213', name: 'DZ' },
    { cn: '美属萨摩亚', en: 'American Samoa', code: '1684', name: 'AS' },
    { cn: '安道尔', en: 'Andorra', code: '376', name: 'AD' },
    { cn: '安哥拉', en: 'Angola', code: '244', name: 'AO' },
    { cn: '安圭拉', en: 'Anguilla', code: '1264', name: 'AI' },
    { cn: '南极洲', en: 'Antarctica', code: '672', name: 'AQ' },
    { cn: '安提瓜和巴布达', en: 'Antigua and Barbuda', code: '1268', name: 'AG' },
    { cn: '阿根廷', en: 'Argentina', code: '54', name: 'AR' },
    { cn: '亚美尼亚', en: 'Armenia', code: '374', name: 'AM' },
    { cn: '阿鲁巴', en: 'Aruba', code: '297', name: 'AW' },
    { cn: '澳大利亚', en: 'Australia', code: '61', name: 'AU' },
    { cn: '奥地利', en: 'Austria', code: '43', name: 'AT' },
    { cn: '阿塞拜疆', en: 'Azerbaijan', code: '994', name: 'AZ' },
    { cn: '巴林', en: 'Bahrain', code: '973', name: 'BH' },
    { cn: '孟加拉国', en: 'Bangladesh', code: '880', name: 'BD' },
    { cn: '巴巴多斯', en: 'Barbados', code: '1246', name: 'BB' },
    { cn: '白俄罗斯', en: 'Belarus', code: '375', name: 'BY' },
    { cn: '比利时', en: 'Belgium', code: '32', name: 'BE' },
    { cn: '伯利兹', en: 'Belize', code: '501', name: 'BZ' },
    { cn: '贝宁', en: 'Benin', code: '229', name: 'BJ' },
    { cn: '百慕大', en: 'Bermuda', code: '1441', name: 'BM' },
    { cn: '不丹', en: 'Bhutan', code: '975', name: 'BT' },
    { cn: '玻利维亚', en: 'Bolivia', code: '591', name: 'BO' },
    { cn: '波黑', en: 'Bosnia and Herzegovina', code: '387', name: 'BA' },
    { cn: '博茨瓦纳', en: 'Botswana', code: '267', name: 'BW' },
    { cn: '巴西', en: 'Brazil', code: '55', name: 'BR' },
    { cn: '英属维尔京群岛', en: 'British Virgin Islands', code: '1284', name: 'IO' },
    { cn: '文莱', en: 'Brunei Darussalam', code: '673', name: 'BN' },
    { cn: '保加利亚', en: 'Bulgaria', code: '359', name: 'BG' },
    { cn: '布基纳法索', en: 'Burkina Faso', code: '226', name: 'BF' },
    { cn: '缅甸', en: 'Myanmar', code: '95', name: 'MM' },
    { cn: '布隆迪', en: 'Burundi', code: '257', name: 'BI' },
    { cn: '喀麦隆', en: 'Cameroon', code: '237', name: 'CM' },
    { cn: '加拿大', en: 'Canada', code: '1', name: 'CA' },
    { cn: '佛得角', en: 'Cape Verde', code: '238', name: 'CV' },
    { cn: '开曼群岛', en: 'Cayman Islands', code: '1345', name: 'KY' },
    { cn: '中非', en: 'Central African Republic', code: '236', name: 'CF' },
    { cn: '乍得', en: 'Chad', code: '235', name: 'TD' },
    { cn: '智利', en: 'Chile', code: '56', name: 'CL' },
    { cn: '圣诞岛', en: 'Christmas Island', code: '61', name: 'CX' },
    { cn: '科科斯基林群岛', en: 'Cocos (Keeling) Islands', code: '61', name: 'CC' },
    { cn: '哥伦比亚', en: 'Colombia', code: '57', name: 'CO' },
    { cn: '科摩罗', en: 'Comoros', code: '269', name: 'KM' },
    { cn: '刚果-金', en: 'Democratic Republic of the Congo', code: '243', name: 'CD' },
    { cn: '刚果-布', en: 'Republic of the Congo', code: '242', name: 'CG' },
    { cn: '库克群岛', en: 'Cook Islands', code: '682', name: 'CK' },
    { cn: '哥斯达黎加', en: 'Costa Rica', code: '506', name: 'CR' },
    { cn: '科特迪瓦', en: 'Cote d Ivoire', code: '225', name: 'CI' },
    { cn: '克罗地亚', en: 'Croatia', code: '385', name: 'HR' },
    { cn: '古巴', en: 'Cuba', code: '53', name: 'CU' },
    { cn: '塞浦路斯', en: 'Cyprus', code: '357', name: 'CY' },
    { cn: '捷克', en: 'Czech Republic', code: '420', name: 'CZ' },
    { cn: '丹麦', en: 'Denmark', code: '45', name: 'DK' },
    { cn: '吉布提', en: 'Djibouti', code: '253', name: 'DJ' },
    { cn: '多米尼克', en: 'Dominica', code: '1767', name: 'DM' },
    { cn: '多米尼加', en: 'Dominican Republic', code: '1809', name: 'DO' },
    { cn: '厄瓜多尔', en: 'Ecuador', code: '593', name: 'EC' },
    { cn: '埃及', en: 'Egypt', code: '20', name: 'EG' },
    { cn: '萨尔瓦多', en: 'El Salvador', code: '503', name: 'SV' },
    { cn: '赤道几内亚', en: 'Equatorial Guinea', code: '240', name: 'GQ' },
    { cn: '厄立特里亚', en: 'Eritrea', code: '291', name: 'ER' },
    { cn: '爱沙尼亚', en: 'Estonia', code: '372', name: 'EE' },
    { cn: '埃塞俄比亚', en: 'Ethiopia', code: '251', name: 'ET' },
    { cn: '马尔维纳斯', en: 'Falkland Islands (Malvinas)', code: '500', name: 'FK' },
    { cn: '法罗群岛', en: 'Faroe Islands', code: '298', name: 'FO' },
    { cn: '斐济', en: 'Fiji', code: '679', name: 'FJ' },
    { cn: '芬兰', en: 'Finland', code: '358', name: 'FI' },
    { cn: '法国', en: 'France', code: '33', name: 'FR' },
    { cn: '法属圭亚那', en: 'French Guiana', code: '594', name: 'GF' },
    { cn: '法属波利尼西亚', en: 'French Polynesia', code: '689', name: 'PF' },
    { cn: '加蓬', en: 'Gabon', code: '241', name: 'GA' },
    { cn: '格鲁吉亚', en: 'Georgia', code: '995', name: 'GE' },
    { cn: '德国', en: 'Germany', code: '49', name: 'DE' },
    { cn: '加纳', en: 'Ghana', code: '233', name: 'GH' },
    { cn: '直布罗陀', en: 'Gibraltar', code: '350', name: 'GI' },
    { cn: '希腊', en: 'Greece', code: '30', name: 'GR' },
    { cn: '格陵兰', en: 'Greenland', code: '299', name: 'GL' },
    { cn: '格林纳达', en: 'Grenada', code: '1473', name: 'GD' },
    { cn: '瓜德罗普', en: 'Guadeloupe', code: '590', name: 'BL' },

    { cn: '关岛', en: 'Guam', code: '1671', name: 'GU' },
    { cn: '危地马拉', en: 'Guatemala', code: '502', name: 'GT' },
    { cn: '根西岛', en: 'Guernsey', code: '1481', name: 'GG' },
    { cn: '几内亚', en: 'Guinea', code: '224', name: 'GN' },
    { cn: '几内亚比绍', en: 'Guinea-Bissau', code: '245', name: 'GW' },
    { cn: '圭亚那', en: 'Guyana', code: '592', name: 'GY' },
    { cn: '海地', en: 'Haiti', code: '509', name: 'HT' },
    { cn: '梵蒂冈', en: 'Holy See (Vatican City)', code: '379', name: 'VA' },
    { cn: '洪都拉斯', en: 'Honduras', code: '504', name: 'HN' },
    { cn: '匈牙利', en: 'Hungary', code: '36', name: 'HU' },
    { cn: '冰岛', en: 'Iceland', code: '354', name: 'IS' },
    { cn: '印度', en: 'India', code: '91', name: 'IN' },
    { cn: '印度尼西亚', en: 'Indonesia', code: '62', name: 'ID' },
    { cn: '伊朗', en: 'Iran', code: '98', name: 'IR' },
    { cn: '伊拉克', en: 'Iraq', code: '964', name: 'IQ' },
    { cn: '爱尔兰', en: 'Ireland', code: '353', name: 'IE' },
    { cn: '以色列', en: 'Israel', code: '972', name: 'IL' },
    { cn: '意大利', en: 'Italy', code: '39', name: 'IT' },
    { cn: '牙买加', en: 'Jamaica', code: '1876', name: 'JM' },
    { cn: '约旦', en: 'Jordan', code: '962', name: 'JO' },
    { cn: '哈萨克斯坦', en: 'Kazakhstan', code: '73', name: 'KZ' },
    { cn: '肯尼亚', en: 'Kenya', code: '254', name: 'KE' },
    { cn: '基里巴斯', en: 'Kiribati', code: '686', name: 'KI' },
    { cn: '朝鲜', en: 'North Korea', code: '850', name: 'KP' },
    { cn: '韩国', en: 'South Korea', code: '82', name: 'KR' },
    { cn: '科威特', en: 'Kuwait', code: '965', name: 'KW' },
    { cn: '吉尔吉斯斯坦', en: 'Kyrgyzstan', code: '996', name: 'KG' },
    { cn: '老挝', en: 'Laos', code: '856', name: 'LA' },
    { cn: '拉脱维亚', en: 'Latvia', code: '371', name: 'LV' },
    { cn: '黎巴嫩', en: 'Lebanon', code: '961', name: 'LB' },
    { cn: '莱索托', en: 'Lesotho', code: '266', name: 'LS' },
    { cn: '利比里亚', en: 'Liberia', code: '231', name: 'LR' },
    { cn: '利比亚', en: 'Libya', code: '218', name: 'LY' },
    { cn: '列支敦士登', en: 'Liechtenstein', code: '423', name: 'LI' },
    { cn: '立陶宛', en: 'Lithuania', code: '370', name: 'LT' },
    { cn: '卢森堡', en: 'Luxembourg', code: '352', name: 'LU' },
    { cn: '马其顿', en: 'Macedonia', code: '389', name: 'MK' },
    { cn: '马达加斯加', en: 'Madagascar', code: '261', name: 'MG' },
    { cn: '马拉维', en: 'Malawi', code: '265', name: 'MW' },
    { cn: '马来西亚', en: 'Malaysia', code: '60', name: 'MY' },
    { cn: '马尔代夫', en: 'Maldives', code: '960', name: 'MV' },
    { cn: '马里', en: 'Mali', code: '223', name: 'ML' },
    { cn: '马耳他', en: 'Malta', code: '356', name: 'MT' },
    { cn: '马绍尔群岛', en: 'Marshall Islands', code: '692', name: 'MH' },
    { cn: '马提尼克', en: 'Martinique', code: '596', name: 'MQ' },
    { cn: '毛里塔尼亚', en: 'Mauritania', code: '222', name: 'MR' },
    { cn: '毛里求斯', en: 'Mauritius', code: '230', name: 'MU' },
    { cn: '马约特', en: 'Mayotte', code: '269', name: 'YT' },
    { cn: '墨西哥', en: 'Mexico', code: '52', name: 'MX' },
    { cn: '密克罗尼西亚', en: 'Federated States of Micronesia', code: '691', name: 'FM' },
    { cn: '摩尔多瓦', en: 'Moldova', code: '373', name: 'MD' },
    { cn: '摩纳哥', en: 'Monaco', code: '377', name: 'MC' },
    { cn: '蒙古', en: 'Mongolia', code: '976', name: 'MN' },
    { cn: '蒙特內哥羅', en: 'Montenegro', code: '382', name: 'ME' },
    { cn: '蒙特塞拉特', en: 'Montserrat', code: '1664', name: 'MS' },
    { cn: '摩洛哥', en: 'Morocco', code: '212', name: 'MA' },
    { cn: '莫桑比克', en: 'Mozambique', code: '258', name: 'MZ' },
    { cn: '纳米尼亚', en: 'Namibia', code: '264', name: 'NA' },
    { cn: '瑙鲁', en: 'Nauru', code: '674', name: 'NR' },
    { cn: '尼泊尔', en: 'Nepal', code: '977', name: 'NP' },
    { cn: '荷兰', en: 'Netherlands', code: '31', name: 'NL' },
    // { cn: '荷属安的列斯', en: 'Netherlands Antilles', code: '599', name: 'AN' },
    { cn: '新喀里多尼亚', en: 'New Caledonia', code: '687', name: 'NC' },
    { cn: '新西兰', en: 'New Zealand', code: '64', name: 'NZ' },
    { cn: '尼加拉瓜', en: 'Nicaragua', code: '505', name: 'NI' },
    { cn: '尼日尔', en: 'Niger', code: '227', name: 'NE' },
    { cn: '尼日利亚', en: 'Nigeria', code: '234', name: 'NG' },
    { cn: '纽埃', en: 'Niue', code: '683', name: 'NU' },
    { cn: '诺福克岛', en: 'Norfolk Island', code: '672', name: 'NF' },
    { cn: '北马里亚纳', en: 'Northern Mariana Islands', code: '1670', name: 'MP' },
    { cn: '挪威', en: 'Norway', code: '47', name: 'NO' },
    { cn: '阿曼', en: 'Oman', code: '968', name: 'OM' },
    { cn: '巴基斯坦', en: 'Pakistan', code: '92', name: 'PK' },
    { cn: '巴勒斯坦領土', en: 'Palestinian Territory, Occupied', code: '970', name: 'PS' },
    { cn: '帕劳', en: 'Palau', code: '680', name: 'PW' },
    { cn: '巴拿马', en: 'Panama', code: '507', name: 'PA' },
    { cn: '巴布亚新几内亚', en: 'Papua New Guinea', code: '675', name: 'PG' },
    { cn: '巴拉圭', en: 'Paraguay', code: '595', name: 'PY' },
    { cn: '秘鲁', en: 'Peru', code: '51', name: 'PE' },
    { cn: '波兰', en: 'Poland', code: '48', name: 'PL' },
    { cn: '葡萄牙', en: 'Portugal', code: '351', name: 'PT' },
    { cn: '波多黎各', en: 'Puerto Rico', code: '1809', name: 'PR' },
    { cn: '卡塔尔', en: 'Qatar', code: '974', name: 'QA' },
    { cn: '留尼汪', en: 'Reunion', code: '262', name: 'RE' },
    { cn: '罗马尼亚', en: 'Romania', code: '40', name: 'RO' },
    { cn: '俄罗斯', en: 'Russia', code: '7', name: 'RU' },
    { cn: '卢旺达', en: 'Rwanda', code: '250', name: 'RW' },
    { cn: '圣赫勒拿', en: 'Saint Helena', code: '290', name: 'SH' },
    { cn: '圣基茨和尼维斯', en: 'Saint Kitts and Nevis', code: '1869', name: 'KN' },
    { cn: '圣卢西亚', en: 'Saint Lucia', code: '1758', name: 'LC' },
    { cn: '圣皮埃尔和密克隆', en: 'Saint Pierre and Miquelon', code: '508', name: 'PM' },
    { cn: '圣文森特和格林纳丁斯', en: 'Saint Vincent and the Grenadines', code: '1784', name: 'VC' },
    { cn: '萨摩亚', en: 'Samoa', code: '685', name: 'WS' },
    { cn: '圣马力诺', en: 'San Marino', code: '378', name: 'SM' },
    { cn: '圣多美和普林西比', en: 'Sao Tome and Principe', code: '239', name: 'ST' },
    { cn: '沙特阿拉伯', en: 'Saudi Arabia', code: '966', name: 'SA' },
    { cn: '塞内加尔', en: 'Senegal', code: '221', name: 'SN' },
    { cn: '塞尔维亚', en: 'Serbia', code: '381', name: 'RS' },
    { cn: '塞舌尔', en: 'Seychelles', code: '248', name: 'SC' },
    { cn: '塞拉利', en: 'Sierra Leone', code: '232', name: 'SL' },
    { cn: '新加坡', en: 'Singapore', code: '65', name: 'SG' },
    { cn: '斯洛伐克', en: 'Slovakia', code: '421', name: 'SK' },
    { cn: '斯洛文尼亚', en: 'Slovenia', code: '386', name: 'SI' },
    { cn: '所罗门群岛', en: 'Solomon Islands', code: '677', name: 'SB' },
    { cn: '索马里', en: 'Somalia', code: '252', name: 'SO' },
    { cn: '南非', en: 'South Africa', code: '27', name: 'ZA' },
    { cn: '南蘇丹', en: 'South Sudan', code: '211', name: 'SS' },
    { cn: '西班牙', en: 'Spain', code: '34', name: 'ES' },
    { cn: '斯里兰卡', en: 'Sri Lanka', code: '94', name: 'LK' },
    { cn: '苏丹', en: 'Sudan', code: '249', name: 'SD' },
    { cn: '苏里南', en: 'Suriname', code: '597', name: 'SR' },
    { cn: '斯瓦尔巴岛和扬马延岛', en: 'Svalbard', code: '47', name: 'SJ' },
    { cn: '斯威士兰', en: 'Swaziland', code: '268', name: 'SZ' },
    { cn: '瑞典', en: 'Sweden', code: '46', name: 'SE' },
    { cn: '瑞士', en: 'Switzerland', code: '41', name: 'CH' },
    { cn: '叙利亚', en: 'Syria', code: '963', name: 'SY' },
    { cn: '塔吉克斯坦', en: 'Tajikistan', code: '992', name: 'TJ' },
    { cn: '坦桑尼亚', en: 'Tanzania', code: '255', name: 'TZ' },
    { cn: '泰国', en: 'Thailand', code: '66', name: 'TH' },
    { cn: '巴哈马', en: 'Bahamas', code: '1242', name: 'BS' },
    { cn: '冈比亚', en: 'Gambia', code: '220', name: 'GM' },
    { cn: '多哥', en: 'Togo', code: '228', name: 'TG' },
    { cn: '托克劳', en: 'Tokelau', code: '690', name: 'TK' },
    { cn: '汤加', en: 'Tonga', code: '676', name: 'TO' },
    { cn: '特立尼达和多巴哥', en: 'Trinidad and Tobago', code: '1868', name: 'TT' },
    { cn: '突尼斯', en: 'Tunisia', code: '216', name: 'TN' },
    { cn: '土耳其', en: 'Turkey', code: '90', name: 'TR' },
    { cn: '土库曼斯坦', en: 'Turkmenistan', code: '993', name: 'TM' },
    { cn: '特克斯和凯科斯群岛', en: 'Turks and Caicos Islands', code: '1649', name: 'TC' },
    { cn: '图瓦卢', en: 'Tuvalu', code: '688', name: 'TV' },
    { cn: '乌干达', en: 'Uganda', code: '256', name: 'UG' },
    { cn: '乌克兰', en: 'Ukraine', code: '380', name: 'UA' },
    { cn: '阿拉伯联合酋长国', en: 'United Arab Emirates', code: '971', name: 'AE' },
    { cn: '英国', en: 'United Kingdom', code: '44', name: 'GB' },
    { cn: '美国', en: 'United States', code: '1', name: 'US' },
    { cn: '乌拉圭', en: 'Uruguay', code: '598', name: 'UY' },
    { cn: '乌兹别克斯坦', en: 'Uzbekistan', code: '998', name: 'UZ' },
    { cn: '瓦努阿图', en: 'Vanuatu', code: '678', name: 'VU' },
    { cn: '委内瑞拉', en: 'Venezuela', code: '58', name: 'VE' },
    { cn: '越南', en: 'Vietnam', code: '84', name: 'VN' },
    { cn: '英属维尔京群岛', en: 'Virgin Islands (UK)', code: '1284', name: 'VG' },
    { cn: '美属维尔京群岛', en: 'Virgin Islands (US)', code: '1340', name: 'VI' },
    { cn: '瓦利斯和富图纳', en: 'Wallis and Futuna', code: '681', name: 'WF' },
    { cn: '也门', en: 'Yemen', code: '967', name: 'YE' },
    { cn: '赞比亚', en: 'Zambia', code: '260', name: 'ZM' },
    { cn: '津巴布韦', en: 'Zimbabwe', code: '263', name: 'ZW' }
  ]
};

export default APP;
